[general]
live_config_reload = true

[window]
opacity = 0.3

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Regular" }
size = 9.7

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Always" }
blink_interval = 300
blink_timeout = 5

[colors.primary]
background = "#f8f8ba"
foreground = "#181818"

[colors.normal]
black   = "#4f5a5e"
red     = "#d00000"
green   = "#007f2f"
yellow  = "#b88600"
blue    = "#0057d8"
magenta = "#8800aa"
cyan    = "#008a9e"
white   = "#dce6e7"

[colors.bright]
black   = "#89969c"
red     = "#ff3030"
green   = "#00b94a"
yellow  = "#e6aa00"
blue    = "#2c7cff"
magenta = "#b44ad8"
cyan    = "#00bcd4"
white   = "#ebeef0"

